export const ROLES = {
  SUPER_ADMIN: 'ROLE_SUPER_ADMIN',
  ADMIN: 'ROLE_ADMIN',
  HR_MANAGER: 'ROLE_HR_MANAGER',
  HR_EXECUTIVE: 'ROLE_HR_EXECUTIVE',
  FINANCE_MANAGER: 'ROLE_FINANCE_MANAGER',
  ACCOUNTANT: 'ROLE_ACCOUNTANT',
  PAYROLL_MANAGER: 'ROLE_PAYROLL_MANAGER',
  INVENTORY_MANAGER: 'ROLE_INVENTORY_MANAGER',
  WAREHOUSE_MANAGER: 'ROLE_WAREHOUSE_MANAGER',
  PROCUREMENT_MANAGER: 'ROLE_PROCUREMENT_MANAGER',
  PURCHASE_MANAGER: 'ROLE_PURCHASE_MANAGER',
  SALES_MANAGER: 'ROLE_SALES_MANAGER',
  CRM_MANAGER: 'ROLE_CRM_MANAGER',
  PROJECT_MANAGER: 'ROLE_PROJECT_MANAGER',
  MANUFACTURING_MANAGER: 'ROLE_MANUFACTURING_MANAGER',
  AUDITOR: 'ROLE_AUDITOR',
  EMPLOYEE: 'ROLE_EMPLOYEE'
};

export const ROLE_LABELS = {
  ROLE_SUPER_ADMIN: 'Super Admin',
  ROLE_ADMIN: 'Administrator',
  ROLE_HR_MANAGER: 'HR Manager',
  ROLE_HR_EXECUTIVE: 'HR Executive',
  ROLE_FINANCE_MANAGER: 'Finance Manager',
  ROLE_ACCOUNTANT: 'Accountant',
  ROLE_PAYROLL_MANAGER: 'Payroll Manager',
  ROLE_INVENTORY_MANAGER: 'Inventory Manager',
  ROLE_WAREHOUSE_MANAGER: 'Warehouse Manager',
  ROLE_PROCUREMENT_MANAGER: 'Procurement Manager',
  ROLE_PURCHASE_MANAGER: 'Purchase Manager',
  ROLE_SALES_MANAGER: 'Sales Manager',
  ROLE_CRM_MANAGER: 'CRM Manager',
  ROLE_PROJECT_MANAGER: 'Project Manager',
  ROLE_MANUFACTURING_MANAGER: 'Manufacturing Manager',
  ROLE_AUDITOR: 'Auditor & Compliance',
  ROLE_EMPLOYEE: 'Employee'
};

export const MODULE_PERMISSIONS = {
  DASHBOARD: ['*'],
  HR: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE],
  FINANCE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.FINANCE_MANAGER, ROLES.ACCOUNTANT, ROLES.PAYROLL_MANAGER, ROLES.AUDITOR],
  INVENTORY: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.INVENTORY_MANAGER, ROLES.WAREHOUSE_MANAGER, ROLES.MANUFACTURING_MANAGER],
  PROCUREMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROCUREMENT_MANAGER, ROLES.PURCHASE_MANAGER, ROLES.INVENTORY_MANAGER],
  SALES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SALES_MANAGER, ROLES.CRM_MANAGER],
  OPERATIONS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROJECT_MANAGER, ROLES.MANUFACTURING_MANAGER, ROLES.WAREHOUSE_MANAGER],
  AUDIT: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.AUDITOR],
  SETTINGS: [ROLES.SUPER_ADMIN, ROLES.ADMIN]
};

export function hasPermission(userRoles = [], allowedRoles = []) {
  if (allowedRoles.includes('*')) return true;
  if (userRoles.includes(ROLES.SUPER_ADMIN) || userRoles.includes(ROLES.ADMIN)) return true;
  return userRoles.some(role => allowedRoles.includes(role));
}
